- id: doi:10.1038/s41597-023-02534-z
  image: https://media.springernature.com/full/springer-static/image/art%3A10.1038%2Fs41597-023-02534-z/MediaObjects/41597_2023_2534_Fig1_HTML.png

- id: doi:10.1093/bioinformatics/btad570
  image: images/bte.jpeg

- id: doi:10.1101/2023.05.12.540594
  image: https://www.biorxiv.org/content/biorxiv/early/2023/12/20/2023.05.12.540594/F1.large.jpg

# Article removals
#
# remove correction for A protocol for adding knowledge to Wikidata: aligning resources on human coronaviruses
- id: doi:10.1186/s12915-023-01764-2
  remove: true
