# This is a GitHub Actions workflow file

name: Build Site

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set root url
        run: |
          touch _config.yaml
          echo "root: /" >> _config.yaml

      - name: Build the site
        run: bundle exec jekyll build