# This is a GitHub Actions workflow file

name: Build Site

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: false

      - name: Install dependencies
        run: bundle install

      - name: Set root url
        run: |
          touch _config.yaml
          echo "root: /" >> _config.yaml

      - name: Build the site
        run: bundle exec jekyll build
